#!/bin/sh -ex

MIN_CPU_THRESHOLD_PCT=${MIN_CPU_THRESHOLD_PCT:-0}
MAX_CPU_THRESHOLD_PCT=${MAX_CPU_THRESHOLD_PCT:-100}
MIN_MEM_THRESHOLD_MIB=${MIN_MEM_THRESHOLD_MIB:-0}
MAX_MEM_THRESHOLD_MIB=${MAX_MEM_THRESHOLD_MIB:-4096}
BOTH_THRESHOLDS=${BOTH_THRESHOLDS:-false}
THRESHOLD_PERIOD=${THRESHOLD_PERIOD:-1m0s}
CONTAINER_WARMUP=${CONTAINER_WARMUP:-1m0s}
CONTAINER_COOLDOWN=${CONTAINER_COOLDOWN:-1m0s}
VERBOSE=${VERBOSE:-false}

if [ "$SERVICE" == "" ]; then
  echo No stack/service read from SERVICE environment variable
  exit 1
fi

if [ "$BOTH_THRESHOLDS" == "true" ]; then
  EXTRAFLAGS="$EXTRAFLAGS --and"
fi

if [ "$VERBOSE" == "true" ]; then
  EXTRAFLAGS="$EXTRAFLAGS --verbose"
fi

exec autoscale service ${SERVICE} \
  --min-cpu $MIN_CPU_THRESHOLD_PCT \
  --max-cpu $MAX_CPU_THRESHOLD_PCT \
  --min-mem $MIN_MEM_THRESHOLD_MIB \
  --max-mem $MAX_MEM_THRESHOLD_MIB \
  --period $THRESHOLD_PERIOD \
  --warmup $CONTAINER_WARMUP \
  --cooldown $CONTAINER_COOLDOWN \
  $EXTRAFLAGS
