.catalog:
  name: "Etcd"
  version: "2.3.6-rancher1"
  description: |
    Distributed highly-available key-value store
  minimum_rancher_version: "v0.46.0"
  questions:
    - variable: "REPLICAS"
      description: "Number of Etcd nodes. 3, 5, or 7 are good choices"
      label: "Number of Nodes:"
      required: true
      default: 3
      type: "int"
etcd:
  scale: ${REPLICAS}
  health_check:
    port: 2379
    interval: 7500
    unhealthy_threshold: 2
    request_line: '/health'
    healthy_threshold: 2
    response_timeout: 5000
