nginx:
  image: rancheriodhci/demo-nginx:25
  links:
    - postgres:postgres
    - web:web
  volumes:
    - /www/static
  volumes_from:
    - web
  labels:
    io.rancher.sidekicks: web
    io.rancher.container.hostname_override: "container_name"
    io.rancher.scheduler.affinity:host_label_soft: app=true
  command: /bin/sh -c "sleep 10 && /usr/sbin/nginx"

web:
  image: rancheriodhci/demo-web:25
  expose:
    - "8000"
  volumes:
    - /usr/src/app/static
  command: '/usr/src/app/start_app.sh'
  labels:
    io.rancher.container.hostname_override: "container_name"
    io.rancher.scheduler.affinity:host_label_soft: app=true

postgres:
  image: postgres:9.5.0
  volumes_from:
    - postgres-data
  expose:
    - "5432"
  labels:
    io.rancher.sidekicks: postgres-data
    io.rancher.scheduler.affinity:host_label_soft: app=true

postgres-data:
  image: postgres:9.5.0
  net: none
  labels:
    io.rancher.container.start_once: "true"
    io.rancher.scheduler.affinity:host_label_soft: app=true
  volumes:
    - /var/lib/postgresql
  command: "/bin/true"
