.catalog:
  name: Messageboard
  version: v1.0
  minimum_rancher_version: v1.1.0-dev5
nginx:
  scale: 3
messageboard-lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000